In [21]:
import numpy as np

In [22]:
Probablities = np.array([
[0.05,0.93,0.02,0.00],
[0.10,0.86,0.04,0.00],
[0.00,0.00,0.80,0.20],
[0.50,0.10,0.00,0.40]])

In [23]:
initial_working_state = np.array([0,200,0,0])

In [24]:
working_states = [initial_working_state]

In [25]:
working_states

[array([  0, 200,   0,   0])]

In [26]:
working_states[-1]

array([  0, 200,   0,   0])

In [27]:
for hours in range(2):
    new_state = Probablities@working_states[-1]
    working_states.append(new_state)

In [28]:
working_states

[array([  0, 200,   0,   0]),
 array([186., 172.,   0.,  20.]),
 array([169.26, 166.52,   4.  , 118.2 ])]

# Trying to understand stuff

Breakdown of @ Calculation (Matrix Multiplication)
Here's what happens step-by-step when transition_matrix @ initial_state is calculated:

next_state
[
0
]
=
(
0.8
×
100
)
+
(
0.2
×
50
)
=
80
+
10
=
90
next_state[0]=(0.8×100)+(0.2×50)=80+10=90
next_state
[
1
]
=
(
0.4
×
100
)
+
(
0.6
×
50
)
=
40
+
30
=
70
next_state[1]=(0.4×100)+(0.6×50)=40+30=70
So, the next_state vector [90, 70] represents the new distribution of entities across the two states.

In [19]:
import numpy as np

# Define a 2x2 transition matrix (like a Markov chain matrix)
transition_matrix = np.array([
    [0.8, 0.2],
    [0.4, 0.6]
])

# Define an initial state vector (distribution across two states)
initial_state = np.array([100, 50])

# Calculate the next state by using matrix multiplication (@ operator)
next_state = transition_matrix @ initial_state

print("Transition Matrix:")
print(transition_matrix)

print("\nInitial State:")
print(initial_state)

print("\nNext State (using @ for matrix multiplication):")
print(next_state)


Transition Matrix:
[[0.8 0.2]
 [0.4 0.6]]

Initial State:
[100  50]

Next State (using @ for matrix multiplication):
[90. 70.]
